# Generated by Django 4.2.1 on 2023-05-10 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(max_length=250)),
                ('schedule', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=250)),
                ('files', models.ImageField(upload_to='events/images/<django.db.models.query_utils.DeferredAttribute object at 0x7f1eb30477f0>')),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('rigor_rank', models.IntegerField()),
                ('attendees', models.ManyToManyField(related_name='events_attending', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
