# Generated by Django 4.2.1 on 2023-05-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="files",
            field=models.ImageField(
                upload_to="events/images/<django.db.models.query_utils.DeferredAttribute object at 0x7f11dfad77f0>"
            ),
        ),
    ]
