# Generated by Django 4.2.1 on 2023-05-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_event_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="files",
            field=models.ImageField(blank=True, null=True, upload_to="events/images/"),
        ),
    ]
